### ISSUE TITLE
Add support for launching multiple instances at once..

### ISSUE THREAD

**Issue by diranged** [brantai/python-rightscale#12]
The RightScale API recently added a `count` flag to the `/api/server_arrays/:server_array_id/launch` method allowing many servers to be launched at once. I have not yet tested whether the `python-rightscale` library supports this already or not. Opening this ticket to track testing it though, and implementing the code if necessary.

CC: @siminm

**Comment by fr33jc** [comment]
Something like this should work:

```python
api = rightscale.RightScale()
task = api.server_arrays.launch(res_id=212341003, params={'count': '2'})
```

When you inspect `task` you'll see the API response.  E.g. `task.soul` should contain something like:

```python
{u'actions': [],
 u'links': [{u'href': u'/api/server_arrays/212341003/live/tasks/ae-327031234003',
   u'rel': u'self'}],
 u'summary': u'queued: Launches multiple ServerArray instances through API'}
```

**Comment by diranged** [comment]
Agreed -- this does indeed work. Thanks for closing and testing.
